Revert "Lots of bugfixes"
This reverts commit f09176ab35bbfe32acd4f81b0fea5345681ba143.

diff --git a/password b/password
--- a/password
+++ b/password
@@ -1,17 +1,39 @@
 #!/bin/bash
 # AUTHOR Martin Stenberg <martin@gnutiken.se>
-# VERSION 2012-03-07
+# VERSION 2012-03-06
 set -u
+
 PASSWORDRC="$HOME/.passwordrc";
 EDITOR=${EDITOR:-"vi"}
 
-function get_recipients {
+if [ -f "$PASSWORDRC" ]; then
+    source "$PASSWORDRC"
+else
+    echo "Warning: Missing \"$PASSWORDRC\" file. Generating default file..."
+
+    echo "PASSWORDS=\$HOME/.gnupg/passwords.gpg" > "$PASSWORDRC"
+    echo "PASSWORDS_TMP=\$HOME/.gnupg/passwords.tmp" > "$PASSWORDRC"
+    echo "PASSWORD_LENGTH=24" > "$PASSWORDRC"
+    echo "PWGEN=\"/usr/bin/pwgen -s -c -n -y 24 1\"" > "$PASSWORDRC"
+
     echo "Please enter recipients (this will be the people who will have access to the password file)."
     echo "Seperate recipients with a space. Example: user@domain.tld 5DAF9A31 user2@otherdomain.tld"
     echo -n "RECIPIENTS="; read RECIPIENTS
 
-    echo "RECIPIENTS=\"$RECIPIENTS\"" >> "$PASSWORDRC"
-}
+    echo "RECIPIENTS=\"$RECIPIENTS\"" > "$PASSWORDRC"
+    source "$PASSWORDRC"
+fi
+
+if [ -z "$PASSWORDS" ]; then
+    echo "Error: \"$PASSWORDRC\" is missing a PASSWORDS line!"
+    exit 1
+elif [ -z "$PASSWORDS_TMP" ]; then
+    PASSWORDS_TMP=$(echo "$PASSWORDS" | sed 's/\..\+$//').decrypted.tmp
+    echo "Warning: \"$PASSWORDRC\" is missing a PASSWORD_TMP line. Using default path (\"$PASSWORDS_TMP\")."
+elif [ -z "$RECIPIENTS" ]; then
+    echo "Error: \"$PASSWORDRC\" is missing a RECIPIENTS line!"
+    exit 1
+fi
 
 function get {
     arg_user=""
@@ -23,16 +45,14 @@ function get {
       case $opt in
         u     ) arg_user=1;;
         c     ) arg_clip=1;
-                XCLIP_BASE=$(basename $(echo $XCLIP|cut -d' ' -f1))
-                if [ -z `which $XCLIP_BASE 2>/dev/null` ]; then
-                    echo "Error: Could not find $XCLIP_BASE. Please install $XCLIP_BASE and try again"
+                if [ -z `which xclip 2>/dev/null` ]; then
+                    echo "Error: Could not find xclip. Please install xclip and try again"
                     exit 1
                 fi
                 ;;
         C     ) arg_clipUsr=1;
-                XCLIP_BASE=$(basename $(echo $XCLIP|cut -d' ' -f1))
-                if [ -z `which $XCLIP_BASE 2>/dev/null` ]; then
-                    echo "Error: Could not find $XCLIP_BASE. Please install $XCLIP_BASE and try again"
+                if [ -z `which xclip 2>/dev/null` ]; then
+                    echo "Error: Could not find xclip. Please install xclip and try again"
                     exit 1
                 fi
                 ;;
@@ -43,38 +63,37 @@ function get {
     shift $(($OPTIND - 1))
 
     clip="cat" ;
-    [ -n "$arg_clip" ] && clip="tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|$XCLIP"
-    [ -n "$arg_clipUsr" ] && clip="head -n2|tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|$XCLIP"
+    [ -n "$arg_clip" ] && clip="tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|xclip"
+    [ -n "$arg_clipUsr" ] && clip="head -n2|tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|xclip"
 	[ -n "$arg_passonly" ] && clip="tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'"
 
     if [ -n "$arg_user" ]
     then
-        $GPG -q --use-agent --batch -d ${PASSWORDS}|grep -i -a -A1 -B1 "^[[:blank:]]\+$@"|eval $clip
+        gpg -q --use-agent --batch -d ${PASSWORDS}|grep -i -a -A1 -B1 "^[[:blank:]]\+$@"|eval $clip
     else
-        $GPG -q --use-agent --batch -d ${PASSWORDS}|grep -i -a -A2 "$@"|eval $clip
+        gpg -q --use-agent --batch -d ${PASSWORDS}|grep -i -a -A2 "$@"|eval $clip
     fi
 }
 
 function new {
     PWGEN_BASE=$(basename $(echo $PWGEN|cut -d' ' -f1))
     if [ -z `which $PWGEN_BASE 2>/dev/null` ]; then
-        echo "Warning: Could not find $PWGEN_BASE. Please install $PWGEN_BASE to auto generate password."
+        echo "Error: Could not find $PWGEN_BASE. Please install $PWGEN_BASE and try again"
+        exit 1
     fi
 
     arg_noninteractive=""
     arg_user=""
     arg_clip=""
-    arg_clipUsr=""
     arg_pass=""
     arg_host=""
-    while getopts "ncCu:h:p:" opt
+    while getopts "ncu:h:p:" opt
     do
       case $opt in
         n     ) arg_noninteractive=1;;
         c     ) arg_clip=1;
-                XCLIP_BASE=$(basename $(echo $XCLIP|cut -d' ' -f1))
-                if [ -z `which $XCLIP_BASE 2>/dev/null` ]; then
-                    echo "Error: Could not find $XCLIP_BASE. Please install $XCLIP_BASE and try again"
+                if [ -z `which xclip 2>/dev/null` ]; then
+                    echo "Error: Could not find xclip. Please install xclip and try again"
                     exit 1
                 fi
                 ;;
@@ -105,32 +124,25 @@ function new {
 
     PASS=$($PWGEN)
     if [ -z "$arg_noninteractive" -a -z "$password" ]; then 
-        if [ -z "$PASS" ]; then
-            echo -n "password: "
-        else
-            echo -n "password ($PASS): "
-        fi
+        echo -n "password ($PASS): "
         read password
     fi
     [ -z "$password" ] && password="$PASS";
 
     # Copy password to clipboard if -c
-    [ -n "$arg_clip" ] && echo -n "$password" | $XCLIP
+    [ -n "$arg_clip" ] && echo -n "$password" | xclip
 
-    # Copy username to clipboard if -C
-    [ -n "$arg_clipUsr" ] && echo -n "$user" | $XCLIP
-
-    PASSWORD_DATA=$($GPG -q --use-agent --batch -d ${PASSWORDS}) 
+    PASSWORD_DATA=$(gpg -q --use-agent --batch -d ${PASSWORDS}) 
     if [ $? -ne 0 ]; then
         echo "Failed to add password"
         exit 1
     fi
-    echo -e "${PASSWORD_DATA}\n${host}\n\t${user}\n\t${password}" | $GPG -q --use-agent --batch -e ${RECIPIENTS_ARGS} > ${PASSWORDS_TMP}
+    echo -e "${PASSWORD_DATA}\n${host}\n\t${user}\n\t${password}" | gpg -q --use-agent --batch -e ${RECIPIENTS_ARGS} > ${PASSWORDS}.tmp
     if [ $? -eq 0 ]; then
-        mv ${PASSWORDS_TMP} ${PASSWORDS}
+        mv ${PASSWORDS}.tmp ${PASSWORDS}
     else
         echo "Failed to add password"
-        rm ${PASSWORDS_TMP}
+        rm ${PASSWORDS}.tmp
         exit 1
     fi
 }
@@ -146,13 +158,13 @@ function edit {
 
     OLDMASK=$(umask)
     umask 077
-    $GPG -q --use-agent --batch -d ${PASSWORDS} > ${PASSWORDS_TMP}
+    gpg -q --use-agent --batch -d ${PASSWORDS} > ${PASSWORDS_TMP}
     MTIME_CREATED=$(stat -c "%Y" ${PASSWORDS_TMP})
     $EDITOR ${PASSWORDS_TMP}
     MTIME_EDITED=$(stat -c "%Y" ${PASSWORDS_TMP})
 
     if [ $MTIME_EDITED -gt $MTIME_CREATED ]; then
-        $GPG -q --use-agent --batch -e ${RECIPIENTS_ARGS} ${PASSWORDS_TMP}
+        gpg -q --use-agent --batch -e ${RECIPIENTS_ARGS} ${PASSWORDS_TMP}
         mv ${PASSWORDS_TMP}.gpg ${PASSWORDS}
     fi
 
@@ -177,96 +189,17 @@ function usage {
     echo "  edit               edit passwordfile with ${EDITOR}"
 }
 
-##############################################################################
-# Main
-#
-if [ -f "$PASSWORDRC" ]; then
-    source "$PASSWORDRC"
-else
-    echo "Warning: Missing \"$PASSWORDRC\" file. Generating default file..."
-
-    XCLIP=$(which xclip)
-    if [ -z "$XCLIP" ]; then
-        echo "Warning: You seem to be missing xclip. Please install xclip to fully utilize this program."
-        XCLIP="/usr/bin/xclip" # set default path
-    fi
-
-    PWGEN=$(which pwgen)
-    if [ -z "$PWGEN" ]; then
-        echo "Warning: You seem to be missing pwgen. Please install pwgen to fully utilize this program."
-        PWGEN="/usr/bin/pwgen" # set default path
-    fi
-
-    GPG=$(which gpg)
-    if [ -z "$GPG" ]; then
-        echo "Error: could not find $GPG. Please install gnupg and try again."
-        exit 1
-    fi
-
-    echo "PASSWORDS=\$HOME/.gnupg/passwords.gpg" >> "$PASSWORDRC"
-    if [ -d "/dev/shm" ]; then
-        echo "PASSWORDS_TMP=/dev/shm/$(whoami)_passwords.tmp" >> "$PASSWORDRC"
-    else
-        echo "PASSWORDS_TMP=\$HOME/.gnupg/passwords.tmp" >> "$PASSWORDRC"
-    fi
-    echo "PWGEN=\"$PWGEN -s -c -n -y 24 1\"" >> "$PASSWORDRC"
-    echo "XCLIP=\"$XCLIP\"" >> "$PASSWORDRC"
-    echo "GPG=\"$GPG\"" >> "$PASSWORDRC"
-
-    get_recipients
-
-    source "$PASSWORDRC"
-fi
-
-if [ -z "$PASSWORDS" ]; then
-    echo "Error: \"$PASSWORDRC\" is missing a PASSWORDS line!"
-    exit 1
-elif [ -z "$PASSWORDS_TMP" ]; then
-    PASSWORDS_TMP=$(echo "$PASSWORDS" | sed 's/\..\+$//').decrypted.tmp
-    echo "Warning: \"$PASSWORDRC\" is missing a PASSWORD_TMP line. Using default path (\"$PASSWORDS_TMP\")."
-elif [ -z "$RECIPIENTS" ]; then
-    echo "Error: \"$PASSWORDRC\" is missing a RECIPIENTS line!"
-    get_recipients
-    source "$PASSWORDRC"
-fi
-
-if [ -z `which $GPG 2>/dev/null` ]; then
-    echo "Error: could not find $GPG. Please install gnupg and try again."
-    exit 1
-fi
-
-# Make sure gpg-agent is running
-echo|gpg --use-agent --batch --sign &> /dev/null
-if [ $? -ne 0 ]; then
-    echo "Error: Could not connect to gpg-agent. Please make sure you have a working gpg-agent setup."
+if [ -z `which gpg 2>/dev/null` ]; then
+    echo "Error: could not find gpg. Please install gnupg and try again."
     exit 1
 fi
 
 RECIPIENTS_ARGS=""
 for r in ${RECIPIENTS};do RECIPIENTS_ARGS="${RECIPIENTS_ARGS}-r $r ";done
 
-# Generate new passwords-file if it doesn't exist
-if [ ! -f "$PASSWORDS" ];then
-    VIM_MODELINE="# vim: autoindent nobackup nowritebackup noswapfile bufhidden=wipe foldmethod=indent fdo=insert fcl=all fdl=1"
-    # TODO: EMACS_MODELINE=""
-
-    MODELINE=""
-    [ "$(basename $EDITOR)" == "vim" ] && MODELINE=$VIM_MODELINE
-
-    echo -e $MODELINE | $GPG -q --use-agent --batch -e ${RECIPIENTS_ARGS} > ${PASSWORDS_TMP}
-    if [ $? -eq 0 ]; then
-        mv ${PASSWORDS_TMP} ${PASSWORDS}
-    else
-        echo "Error: $PASSWORDS: Could not create file."
-        rm ${PASSWORDS_TMP}
-        exit 1
-    fi
-fi
-
-# BEGIN Backwards compability
 set +u
 args=$@
-case $(basename $0) in
+case $(basename $0) in 
     passfor     ) cmd="get";;
     newpass     ) cmd="new";;
     editpass    ) cmd="edit";;
@@ -274,7 +207,6 @@ case $(basename $0) in
     *           ) cmd="$1"; shift; args=$@;;
 esac
 set -u
-# END Backwards compability
 
 case $cmd in
     get ) get ${args[@]};;
