added support for getting username to clipboard with -C

diff --git a/password b/password
--- a/password
+++ b/password
@@ -1,6 +1,6 @@
 #!/bin/bash
-# AUTHOR Martin Stenberg <bumbyn@gmail.com>
-# VERSION 2011-02-04
+# AUTHOR Martin Stenberg <martin@gnutiken.se>
+# VERSION 2012-03-06
 set -u
 
 PASSWORDRC="$HOME/.passwordrc";
@@ -38,12 +38,19 @@ fi
 function get {
     arg_user=""
     arg_clip=""
+    arg_clipUsr=""
 	arg_passonly=""
-    while getopts "ucp" opt
+    while getopts "ucCp" opt
     do
       case $opt in
         u     ) arg_user=1;;
         c     ) arg_clip=1;
+                if [ -z `which xclip 2>/dev/null` ]; then
+                    echo "Error: Could not find xclip. Please install xclip and try again"
+                    exit 1
+                fi
+                ;;
+        C     ) arg_clipUsr=1;
                 if [ -z `which xclip 2>/dev/null` ]; then
                     echo "Error: Could not find xclip. Please install xclip and try again"
                     exit 1
@@ -54,15 +61,17 @@ function get {
     done
 
     shift $(($OPTIND - 1))
-    
-    clip="cat" ; [ -n "$arg_clip" ] && clip="tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|xclip"
+
+    clip="cat" ;
+    [ -n "$arg_clip" ] && clip="tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|xclip"
+    [ -n "$arg_clipUsr" ] && clip="head -n2|tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'|xclip"
 	[ -n "$arg_passonly" ] && clip="tail -n1|sed 's/\(^\s\+\|\s\+$\)//g'"
 
     if [ -n "$arg_user" ]
     then
-        gpg -q --batch -d ${PASSWORDS}|grep -i -a -A1 -B1 "^[[:blank:]]\+$@"|eval $clip
+        gpg -q --use-agent --batch -d ${PASSWORDS}|grep -i -a -A1 -B1 "^[[:blank:]]\+$@"|eval $clip
     else
-        gpg -q --batch -d ${PASSWORDS}|grep -i -a -A2 "$@"|eval $clip
+        gpg -q --use-agent --batch -d ${PASSWORDS}|grep -i -a -A2 "$@"|eval $clip
     fi
 }
 
@@ -123,12 +132,12 @@ function new {
     # Copy password to clipboard if -c
     [ -n "$arg_clip" ] && echo -n "$password" | xclip
 
-    PASSWORD_DATA=$(gpg -q --batch -d ${PASSWORDS}) 
+    PASSWORD_DATA=$(gpg -q --use-agent --batch -d ${PASSWORDS}) 
     if [ $? -ne 0 ]; then
         echo "Failed to add password"
         exit 1
     fi
-    echo -e "${PASSWORD_DATA}\n${host}\n\t${user}\n\t${password}" | gpg -q --batch -e ${RECIPIENTS_ARGS} > ${PASSWORDS}.tmp
+    echo -e "${PASSWORD_DATA}\n${host}\n\t${user}\n\t${password}" | gpg -q --use-agent --batch -e ${RECIPIENTS_ARGS} > ${PASSWORDS}.tmp
     if [ $? -eq 0 ]; then
         mv ${PASSWORDS}.tmp ${PASSWORDS}
     else
@@ -149,13 +158,13 @@ function edit {
 
     OLDMASK=$(umask)
     umask 077
-    gpg -q --batch -d ${PASSWORDS} > ${PASSWORDS_TMP}
+    gpg -q --use-agent --batch -d ${PASSWORDS} > ${PASSWORDS_TMP}
     MTIME_CREATED=$(stat -c "%Y" ${PASSWORDS_TMP})
     $EDITOR ${PASSWORDS_TMP}
     MTIME_EDITED=$(stat -c "%Y" ${PASSWORDS_TMP})
 
     if [ $MTIME_EDITED -gt $MTIME_CREATED ]; then
-        gpg -q --batch -e ${RECIPIENTS_ARGS} ${PASSWORDS_TMP}
+        gpg -q --use-agent --batch -e ${RECIPIENTS_ARGS} ${PASSWORDS_TMP}
         mv ${PASSWORDS_TMP}.gpg ${PASSWORDS}
     fi
 
@@ -169,6 +178,7 @@ function usage {
     echo "  get [-u] PATTERN   get password matching hostname pattern PATTERN"
     echo "    -u               match username instead of hostname"
     echo "    -c               copy password to clipboard"
+    echo "    -C               copy username to clipboard"
     echo "    -p               print only password"
     echo "  new [-nc] [-h HOST] [-u USERNAME] [-p PASSWORD]"
     echo "    -n               noninteractive mode"
@@ -187,6 +197,7 @@ fi
 RECIPIENTS_ARGS=""
 for r in ${RECIPIENTS};do RECIPIENTS_ARGS="${RECIPIENTS_ARGS}-r $r ";done
 
+set +u
 args=$@
 case $(basename $0) in 
     passfor     ) cmd="get";;
@@ -195,6 +206,7 @@ case $(basename $0) in
     pass2clip   ) cmd="get"; args=( "-c" "${args[@]}" );;
     *           ) cmd="$1"; shift; args=$@;;
 esac
+set -u
 
 case $cmd in
     get ) get ${args[@]};;
